### ISSUE TITLE
How to do content modeling?

### ISSUE THREAD

**Issue by swapnilmmane** [webiny/write-with-webiny#13]

**Comment by Dsalinasgardon** [comment]
### How to do content modeling?
Software developers are always looking for ways to improve their workflow and create better software. One way to do this is by using content modeling. Content modeling is a technique that helps you organize your code and data so that your application is easy to understand and maintain. 

In this blog post, we will discuss what content modeling is and how you can use it in your own development projects. 

### What is content modeling?
Touch on what is a content model and how does it work

**Benefits of content modeling**
- Consistency
- Reusability
- Adaptability
- Internationalization

### How to create a content model
Analyze
Identify 
Develop

### Building content models using Webiny

**Comment by swapnilmmane** [comment]
Hi @Dsalinasgardon, thank you for sharing the abstract. 
Sorry, it seems that our team should define more information about what is expected in this blog. 
As you are working on [this blog](https://github.com/webiny/write-with-webiny/issues/3), so I am putting this issue on `Hold` for now until we can get some outline and expectations from the team.

Thanks again for your interest!

**Comment by endymion1818** [comment]
Sorry @Dsalinasgardon, as we clarified over Slack, we're dropping this article, but we're keen for you to stick with us and pick something else up.
